extends: 'eslint:recommended'

root: true

plugins:
  - mocha

parserOptions:
  ecmaVersion: 2018
  sourceType: script

env:
  es6: true
  node: true
  mocha: true

rules:
  arrow-parens:
    - "error"
    - "always"
  computed-property-spacing:
    - "error"
    - never
  eol-last:
    - "error"
  indent:
    - "error"
    - 2
    - SwitchCase: 1
  keyword-spacing:
    - "error"
  linebreak-style:
    - "error"
    - unix
  "mocha/no-exclusive-tests":
    - "error"
  "mocha/no-identical-title":
    - "error"
  "mocha/no-skipped-tests":
    - "warn"
  no-multiple-empty-lines:
    - "error"
    - { max: 1, maxEOF: 1 }
  no-unused-vars:
    - "error"
    - { argsIgnorePattern: "_" }
  no-var:
    - "error"
  object-curly-spacing:
    - "error"
    - always
  prefer-const:
    - "error"
  quotes:
    - "error"
    - single
  semi:
    - "error"
    - always
  space-before-blocks:
    - "error"
  space-before-function-paren:
    - "error"
    - { anonymous: never, named: never, asyncArrow: ignore }
  space-in-parens:
    - "error"
  space-infix-ops:
    - "error"
