x-common-env: &cenv
  MINIO_BUCKET: "test-bucket"
  MINIO_ROOT_USER: "pix-admin"
  MINIO_ROOT_PASSWORD: "pix-admin-password"
  BUCKET_NAME: "test-bucket"

version: '3'

services:
  database:
    container_name: database
    image: postgres:14.8-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: unless-stopped
    volumes:
      - ./local-setup/script/create-databases.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2023-08-16T20-17-30Z
    environment:
      <<: *cenv
    ports:
      - 9000:9000
      - 9001:9001
    entrypoint: ["minio", "server", "/data", "--console-address", ":9001"]

  init-minio:
    image: quay.io/minio/minio:RELEASE.2023-08-16T20-17-30Z
    environment:
      <<: *cenv
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/bash -c "
      mc config host add myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      mc rm -r --force --dangerous myminio/$${BUCKET_NAME};
      mc mb myminio/$${BUCKET_NAME};
      mc policy set download myminio/$${BUCKET_NAME};
      mc policy add readwrite myminio/$${BUCKET_NAME};"
