version: '3'

services:

  database:
    container_name: database
    image: postgres:14.10-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: unless-stopped
    volumes:
      - ./local-setup/script/create-databases.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.3-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
