version: '3'

services:

  replication-source:
    container_name: replication-source-db
    image: postgres:12.4-alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: replication_source
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: unless-stopped

  replication-target:
    container_name: replication-target-db
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: replication_target
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: unless-stopped
