version: '3'

services:

  database-cpf-export-local:
    container_name: database-cpf-export-local
    image: postgres:15.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: unless-stopped
    volumes:
      - ./create-table.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
