async function getLearningContent() {
  return Promise.resolve([
    {
      'id': 'ca47a7a8-4dc9-42bd-a1ac-4b1e849a054b',
      'shortId': '8a74eba3',
      'slug': 'ranger-fichiers-ind',
      'title': 'Organiser les fichiers de son ordinateur',
      'filename': '12_RangerFichiers_IND.json',
      'level': 'independent',
      'duration': 10,
      'objectives': 'Trouver un fichier en suivant son chemin d’accès, Comprendre le rôle d’un gestionnaire de fichiers, Utiliser un gestionnaire de fichiers pour consulter et organiser des dossiers et des fichiers',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'c89e0ac4-e989-45e7-924d-3e28f417e03d',
      'shortId': '06ab78b4',
      'slug': 'essentiel-ranger-fichiers',
      'title': 'Fichiers et dossiers : l’essentiel sur un ordinateur',
      'filename': '12_RangerFichiers_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': 'Faire la différence entre un fichier et un dossier, Savoir créer un dossier et y ranger des fichiers, Savoir à quoi sert la corbeille et comment l’utiliser',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '0d8e8473-96d2-4a7a-bfa5-8cbf14a6e7e7',
      'shortId': 'e2a291d1',
      'slug': 'repondre-mail-nov',
      'title': ' Vous avez reçu un mail',
      'filename': '21_RepondreMail_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Consulter ses mails dans la messagerie électronique</p>, <p>Lire les informations principales d’un mail dans la boîte de réception</p>, <p>Répondre à un mail</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '92d3528c-3404-4ba5-808e-215e0787bf60',
      'shortId': '93c3b007',
      'slug': 'cyber-antivirus',
      'title': 'Renforcez la protection de vos appareils contre les logiciels malveillants',
      'filename': 'CYAntivirus_IND.json',
      'level': 'independent',
      'duration': 10,
      'objectives': '<p>Comprendre que les attaques par logiciels malveillants exploitent des failles des systèmes d’exploitation</p>, <p>Connaître le rôle des logiciels antivirus</p>, <p>Comprendre que les mises à jour renforcent la protection des appareils</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '0aed9f0d-e735-48f8-900b-32cc4251dd0e',
      'shortId': '8ee73f2b',
      'slug': 'cyber-gestionnaire',
      'title': 'Un coffre-fort pour vos mots de passe',
      'filename': 'CYGestionMDP_IND.json',
      'level': 'independent',
      'duration': 10,
      'objectives': '<p>Connaître le rôle et le fonctionnement de base d’un gestionnaire de mots de passe</p>, <p>Comprendre l’importance du mot de passe maître</p>, <p>Savoir quel type de gestionnaire est adapté à ses besoins</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '93c4a755-7576-47b7-b2f0-9001ca9c2e57',
      'shortId': '09afbfa2',
      'slug': 'cyber-proteger-mdp',
      'title': 'Protéger ses mots de passe',
      'filename': 'CYGestionMDP_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Savoir gérer ses mots de passe de manière sécurisée</p>, <p>Savoir réagir en cas d’oubli de mot de passe</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'fbde0db0-344a-4b98-a9b4-68f74f358629',
      'shortId': '0389ba82',
      'slug': 'cyber-mdp-fort',
      'title': 'Un mot de passe fort, c’est quoi ?',
      'filename': 'CYMDP_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Comprendre l’importance d’avoir des mots de passe forts</p>, <p>Identifier ce qu’est un mot de passe fort</p>, <p>Savoir créer un mot de passe fort en suivant des règles simples</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '5b9c6c6b-3cfa-4004-8769-ac745616d540',
      'shortId': '9c41e513',
      'slug': 'mfa-authentification-multifacteur',
      'title': 'Plus puissante qu’un mot de passe : l’authentification multifacteur',
      'filename': 'CYMFA_IND.json',
      'level': 'independent',
      'duration': 10,
      'objectives': '<p>Comprendre le principe de l’authentification multifacteur</p>, <p>Différencier les trois types de facteurs d’authentification</p>, <p>Connaître les limites des trois types de facteurs d’authentification</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'ddaa2f81-4855-4606-bcae-d21e40ac9969',
      'shortId': 'ea6796a0',
      'slug': 'cyber-double-authentification',
      'title': 'Protéger ses données en ligne avec la double authentification',
      'filename': 'CYMFA_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Différencier le rôle d’un identifiant et le rôle d’un mot de passe</p>, <p>Comprendre à quoi sert la double authentification</p>, <p>Identifier des situations où la double authentification est utilisée</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'f924b0e8-0b2b-4b8e-b7fe-f1b14e9b8094',
      'shortId': '4fb0e2cd',
      'slug': 'cyber-ingenierie-sociale',
      'title': 'Cyberattaques : quand l’ingénierie sociale s’en mêle !',
      'filename': 'CYPhishing_AVA.json',
      'level': 'advanced',
      'duration': 10,
      'objectives': '<p>Identifier les attaques par ingénierie sociale les plus courantes</p>, <p>Connaître les mécanismes sur lesquels s’appuie l’ingénierie sociale</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '70813abe-7423-426d-80c8-b1f0271ae0b4',
      'shortId': '82920553',
      'slug': 'anatomie-message-arnaque',
      'title': 'Anatomie d’un message d’arnaque',
      'filename': 'CYPhishing_IND.json',
      'level': 'independent',
      'duration': 10,
      'objectives': '<p>Connaître la définition du hameçonnage (phishing)</p>, <p>Reconnaître des indices caractéristiques d’un message d’arnaque</p>, <p>Agir face à un message d’arnaque</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'd86262d1-bf99-41d3-abc5-ef39c7d05288',
      'shortId': '975d25d1',
      'slug': 'cyber-message-arnaque',
      'title': 'Vous avez un nouveau message ✉️ : attention aux arnaques',
      'filename': 'CYPhishing_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Reconnaître une tentative d’arnaque par message (SMS, messagerie instantanée)</p>, <p>Adopter un comportement de prudence à la réception d’un nouveau message</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'f8fdc1be-1a2c-4708-9f2e-b388e82d2f8a',
      'shortId': '448b2c93',
      'slug': 'cyber-virus-nov',
      'title': 'Mon ordinateur a été infecté par un virus : comment est-ce possible ?',
      'filename': 'CYVirus_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Découvrir les effets causés par des logiciels malveillants</p>, <p>Comprendre d’où viennent les logiciels malveillants</p>, <p>Reconnaître des situations à risque et les éviter</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'bc6d164f-26bd-4f58-9925-8cf5365e2ca6',
      'shortId': '43e420e6',
      'slug': 'ia-def-ind',
      'title': 'Une IA botaniste : un cas d’apprentissage supervisé.',
      'filename': 'IADefinition_IND.json',
      'level': 'independent',
      'duration': 10,
      'objectives': '<p>Décrire le fonctionnement de l’apprentissage automatique supervisé<br></p>, <p>Identifier les limites de l’apprentissage automatique supervisé</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '40ab5711-4025-4052-a269-00fd0448d60a',
      'shortId': 'cc0cbab7',
      'slug': 'ia-dit-ia',
      'title': 'IA, vous avez dit IA ? ',
      'filename': 'IADefinition_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Connaître une définition simple de l’intelligence artificielle</p>, <p>Identifier des types de tâches que font les logiciels d’IA</p>, <p>Repérer l’utilisation de l’IA dans des services numériques quotidiens</p>',
      'isBeta': false,
      'visibility': 'public',
    },
    {
      'id': 'ccad60a8-6c48-4d91-84cb-d717a1ea4918',
      'shortId': '5bb2f995',
      'slug': 'iagenbiais-avance',
      'title': 'Comment sont cadrées les réponses des logiciels d’IA ?',
      'filename': 'IAGenBiais_AVA.json',
      'level': 'advanced',
      'duration': 10,
      'objectives': '<p>Expliquer pourquoi on contraint les IA génératives à respecter des valeurs morales</p>, <p>Savoir décrire des méthodes d’alignement des IA génératives</p>, <p>Identifier les enjeux politiques et sociaux de l’alignement des IA génératives</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'a1eea948-2125-488f-8006-9f85e646830d',
      'shortId': '163b520e',
      'slug': 'ia-bias-ind',
      'title': 'Les biais des IA génératives',
      'filename': 'IAGenBiais_IND.json',
      'level': 'independent',
      'duration': 10,
      'objectives': '<p>Repérer des biais ou des stéréotypes présents dans les contenus</p>, <p>Expliquer comment une IA générative reproduit des biais présents dans les données de son entraînement</p>, <p>Utiliser l’IA en étant vigilant sur ses propres biais, comme le biais de confirmation</p>',
      'isBeta': false,
      'visibility': 'public',
    },
    {
      'id': 'c8607621-09ab-4601-be7d-68ed9c914c30',
      'shortId': '9be9cfae',
      'slug': 'ia-hallu',
      'title': 'Elles hallucinent, ces IA génératives ! ',
      'filename': 'IAGenBiais_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Savoir que les IA génératives peuvent faire des erreurs</p>, <p>Connaître les causes principales des erreurs des IA génératives</p>, <p>Connaître les bons réflexes à adopter face aux réponses des IA génératives</p>',
      'isBeta': false,
      'visibility': 'public',
    },
    {
      'id': '178e7bb5-9d0a-43e6-b0a1-c7039bd7e2a8',
      'shortId': 'e5019e0e',
      'slug': 'ia-biais-ind-alt',
      'title': 'Les biais des lA',
      'filename': 'IAGenBiais_NOV_alt.json',
      'level': 'independent',
      'duration': 10,
      'objectives': '<p>Repérer des biais ou des stéréotypes présents dans les contenus. </p>, <p>Expliquer comment une IA générative reproduit les biais présents dans les données de son entraînement.</p>, <p>Utiliser l’IA en étant vigilant sur ses propres biais, comme le biais de confirmation.</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '8266f923-4255-46ba-97c5-61cbdbe18986',
      'shortId': 'e71a9bdd',
      'slug': 'iagenethiquenov',
      'title': 'Ce qu’il faut éviter de dire à une IA générative',
      'filename': 'IAGenEthique_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Comprendre que les conversations avec les IA génératives sont réutilisées</p>, <p>Savoir rédiger un prompt qui n’inclut pas d’informations personnelles</p>, <p>Connaître les risques du partage de données sensibles avec l’IA générative</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '4b3e2191-b9e6-4539-90bb-ef438895c157',
      'shortId': 'a0bf86e9',
      'slug': 'outils-ia',
      'title': 'La boîte à outils des IA',
      'filename': 'IAGenFonction_Ava.json',
      'level': 'advanced',
      'duration': 10,
      'objectives': 'Comprendre à quoi servent les appels d’outils dans les logiciels d’IA conversationnelle, Comprendre le fonctionnement des appels d’outils par les logiciels d’IA, Identifier des situations dans lesquelles l’appel d’outil par le logiciel d’IA est utile',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'd03cef94-74af-463d-8901-c886b48d6e0b',
      'shortId': '76961c86',
      'slug': 'ia-fonctionnement-ind',
      'title': 'Comment l’IA générative apprend-elle à discuter avec vous ?',
      'filename': 'IAGenFonction_IND.json',
      'level': 'independent',
      'duration': 10,
      'objectives': '<p>Savoir expliquer les 3 étapes de l’entraînement des IA génératives de texte</p>, <p>Identifier les interventions des humains dans chacune de ces étapes</p>',
      'isBeta': false,
      'visibility': 'public',
    },
    {
      'id': '71618929-fcc9-415e-a3f3-9582545d7a78',
      'shortId': '797ea8fb',
      'slug': 'ia-fonctionnement-debut',
      'title': 'Comment font les IA génératives pour répondre à nos demandes ?',
      'filename': 'IAGenFonction_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Définir simplement un logiciel d’IA générative</p>, <p>Expliquer comment un logiciel d’IA générative construit ses réponses</p>',
      'isBeta': false,
      'visibility': 'public',
    },
    {
      'id': '8343e9c1-5b46-4500-ab85-54061e0c4712',
      'shortId': '6bf111e0',
      'slug': 'les-ia-generatives-consomment',
      'title': 'L‘IA générative, ça consomme !',
      'filename': 'IAGenImpact_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Identifier le matériel utilisé par les IA génératives</p>, <p>Expliquer l‘énergie consommée par les IA génératives</p>',
      'isBeta': false,
      'visibility': 'public',
    },
    {
      'id': '7a38c90d-9937-4497-bee3-fe58541af420',
      'shortId': '4eacd0c3',
      'slug': 'prompt-intermediaire',
      'title': 'J’améliore mes prompts !',
      'filename': 'IAGenPrompt_IND.json',
      'level': 'independent',
      'duration': 10,
      'objectives': '<p>Écrire des prompts efficaces</p>, <p> Évaluer de manière critique la réponse du logiciel&nbsp;d’IA générative</p>, <p>Améliorer la réponse donnée par le logiciel d’IA générative</p>',
      'isBeta': false,
      'visibility': 'public',
    },
    {
      'id': 'cf183961-e85a-421d-a316-05870191ff82',
      'shortId': '4920d56c',
      'slug': 'ia-premier-prompt',
      'title': 'Mon premier prompt !',
      'filename': 'IAGenPrompt_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Savoir ce qu’est un prompt</p>, <p>Formuler des prompts clairs et précis pour des tâches de base</p>, <p>Vérifier la réponse du logiciel d’IA générative et lui demander des précisions si nécessaire</p>',
      'isBeta': false,
      'visibility': 'public',
    },
    {
      'id': '8aa17e6d-3470-479d-838d-ff6923de6686',
      'shortId': '05b24fee',
      'slug': 'ia-deepfakes',
      'title': 'Les deepfakes (hypertrucages) : c’est quoi ?',
      'filename': 'IAInfox_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Savoir que des médias en ligne peuvent être créés avec l‘intelligence artificielle (IA)</p>, <p>Connaître la notion de deepfake (hypertrucage)</p>, <p>Repérer les intentions des auteurs de deepfakes (hypertrucages)</p>',
      'isBeta': false,
      'visibility': 'public',
    },
    {
      'id': '2a4cbdcc-0d75-4b42-bd41-592acc08abb4',
      'shortId': 'dd49b3d9',
      'slug': 'nr-coulisses-centre-donnees',
      'title': 'Dans les coulisses d’un centre de données',
      'filename': 'NR-Datacenter-IND.json',
      'level': 'independent',
      'duration': 10,
      'objectives': '<p>Connaître les principaux systèmes qui composent un centre de données.</p>, <p>Comprendre l’impact environnemental du refroidissement des centres de données.</p>, <p>Comprendre l’impact des nouveaux usages numériques sur les centres de données.</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '05ff418a-3329-44bf-9094-14014301df3c',
      'shortId': 'da86e4a7',
      'slug': 'centre-de-donnee-novice',
      'title': 'L’impact caché de nos usages numériques en ligne',
      'filename': 'NR-Datacenter-NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Identifier le rôle des centres de données dans nos usages en ligne</p>, <p>Connaître les deux postes principaux de consommation d’énergie des centres de données (fonctionnement et refroidissement)</p>, <p>Repérer que certaines activités en ligne utilisent plus d’énergie que d’autres</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '2b01b6af-1b32-44ac-9f64-9fb064fa2971',
      'shortId': 'dd3ddf6c',
      'slug': 'nr-obsolescence-programmee',
      'title': 'En finir avec l’obsolescence programmée ? ',
      'filename': 'NR-Durabilite-AVA.json',
      'level': 'advanced',
      'duration': 10,
      'objectives': '<p>Connaître les impacts de la fabrication d’un équipement informatique</p>, <p>Identifier des pratiques d’obsolescence programmée</p>, <p>Connaître le principe de l’économie circulaire</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '7ee3ef2d-b29d-4029-86cf-f88ceb4ddea2',
      'shortId': 'e89cf72c',
      'slug': 'centre-de-donnees-mieux-faire',
      'title': 'Centre de données : peut-on mieux faire ?',
      'filename': 'NR_Datacenter_AVA.json',
      'level': 'advanced',
      'duration': 10,
      'objectives': '<p>Décrire les impacts environnementaux des centres de données</p>, <p>Identifier des changements de pratiques nécessaires pour réduire l’impact environnemental des centres de données </p>, <p>Connaître des solutions techniques pour réduire les impacts environnementaux des centres de données</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '3f7c9a42-0d2c-4c91-bf8a-7e6b8f8d8f1a',
      'shortId': '0d64b1f9',
      'slug': 'evaluation-impacts-environnementaux-numerique',
      'title': 'Comment sont évalués les impacts environnementaux du numérique ?',
      'filename': 'NR_Evaluation_IND.json',
      'level': 'independent',
      'duration': 10,
      'objectives': '<p>Identifier les trois composantes du secteur numérique</p>, <p>Lister des critères pour évaluer les impacts environnementaux du secteur numérique</p>, <p>Connaître les quatre étapes du cycle de vie d’un appareil numérique</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '8d1ff1e0-1e14-448b-afd9-e4b73820fa8b',
      'shortId': '8457471e',
      'slug': 'nr-durabilite-nov',
      'title': 'Pourquoi conserver son smartphone plus longtemps ?',
      'filename': 'NR_durabilite_Nov.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Identifier les impacts environnementaux de la fabrication des smartphones.</p>, <p>Connaître les gestes pour prolonger la durée de vie d’un smartphone.</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '0850d77c-a846-41a4-bf10-d6bd82e2f31e',
      'shortId': '144ee2d7',
      'slug': 'surequipement',
      'title': '30 milliards d’appareils numériques : la folie du suréquipement',
      'filename': 'NR_surequipement_NOV.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Connaître le phénomène de suréquipement numérique.</p>, <p>Savoir que les équipements numériques consomment de l’électricité, même en veille.</p>, <p>Connaître le juste besoin et des gestes pour limiter le gaspillage d’énergie des appareils numériques.</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '5df14039-803b-4db4-9778-67e4b84afbbd',
      'shortId': 'ecc13f55',
      'slug': 'adresse-ip-publique-et-vous',
      'title': 'L‘adresse IP publique : ce qu‘elle révèle sur vous !',
      'filename': 'adresse-ip-publique-et-vous.json',
      'level': 'independent',
      'duration': 10,
      'objectives': 'Comprendre la fonction des adresses IP publiques, Connaître les informations personnelles dévoilées par l‘adresse IP publique (IPv4), Distinguer les adresses IP publiques des adresses IP privées',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '9beb922f-4d8e-495d-9c85-0e7265ca78d6',
      'shortId': 'e074af34',
      'slug': 'au-dela-des-mots-de-passe',
      'title': 'Au-delà des mots de passe : comment s’authentifier ?',
      'filename': 'au-dela-des-mots-de-passe.json',
      'level': 'novice',
      'duration': 5,
      'objectives': '<p>Comprendre le principe et l’intérêt d’une double authentification</p>, <p>Effectuer en pratique une double authentification</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '6282925d-4775-4bca-b513-4c3009ec5886',
      'shortId': '6a68bf32',
      'slug': 'bac-a-sable',
      'title': 'Bac à sable',
      'filename': 'bac-a-sable.json',
      'level': 'novice',
      'duration': 5,
      'objectives': 'Non régression fonctionnelle',
      'isBeta': true,
      'visibility': 'private',
    },
    {
      'id': '654c44dc-0560-4acc-9860-4a67c923577f',
      'shortId': '740d5aa9',
      'slug': 'bases-clavier-1',
      'title': 'Les bases du clavier sur ordinateur 1/2',
      'filename': 'bases-clavier-ordinateur-1.json',
      'level': 'novice',
      'duration': 30,
      'objectives': '<p>Repérer les touches de base du clavier</p>, <p>Taper des mots simples avec un clavier</p>, <p>Modifier du texte</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'bb0a4ed3-1b49-4782-b867-05ade0868c4f',
      'shortId': '31ca924a',
      'slug': 'bases-clavier-2',
      'title': 'Les bases du clavier sur ordinateur 2/2',
      'filename': 'bases-clavier-ordinateur-2.json',
      'level': 'novice',
      'duration': 30,
      'objectives': '<p>Taper du texte comprenant des majuscules, chiffres et caractères spéciaux</p>, <p>Comprendre la place des caractères sur les touches</p>, <p>Taper des caractères qui nécessitent d’utiliser plusieurs touches</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'f7b3a2e1-0d5c-4c6c-9c4d-1a3d8f7e9f5d',
      'shortId': '9d4dcab8',
      'slug': 'bien-ecrire-son-adresse-mail',
      'title': 'Bien écrire une adresse mail',
      'filename': 'bien-ecrire-son-adresse-mail.json',
      'level': 'novice',
      'duration': 10,
      'objectives': 'Reconnaître les différentes parties d’une adresse mail et les identifier sur des exemples, Associer chaque partie d‘une adresse mail à sa fonction, Écrire une adresse mail correctement, en évitant les erreurs courantes',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '01151659-77c1-41cc-8724-89091357af3d',
      'shortId': 'e67ec5d0',
      'slug': 'chatgpt-vraiment-neutre',
      'title': 'ChatGPT est-il vraiment neutre ?',
      'filename': 'chatgpt-vraiment-neutre.json',
      'level': 'advanced',
      'duration': 10,
      'objectives': '<p>Connaître les origines des biais des LLM</p>, <p>Générer et analyser des résultats biaisés de LLM</p>, <p>Comparer les résultats de différents LLM</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'd4c4a2b2-0046-471d-ad9c-15f9cfc8f1f6',
      'shortId': '7762efcb',
      'slug': 'comment-envoyer-un-mail',
      'title': 'Comment envoyer un mail ? ',
      'filename': 'comment-envoyer-un-mail.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Écrire et envoyer un mail</p>, <p>Comprendre et utiliser les principaux champs d‘un mail (De, À, Objet)</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'a9e7dda1-fbcc-43a0-a9b4-90056548a4ae',
      'shortId': '15894c06',
      'slug': 'controle-parental',
      'title': 'Le contrôle parental',
      'filename': 'controle-parental.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Savoir ce qu’est le contrôle parental</p>, <p>Comprendre à quoi sert le contrôle parental</p>, <p>Savoir où trouver le contrôle parental et comment l’activer</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '1c765240-c790-4f32-8ec0-bc9945bcc5ce',
      'shortId': 'c6437577',
      'slug': 'decouverte-de-l-ent',
      'title': 'À la découverte de l’ENT',
      'filename': 'decouverte-de-l-ent.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Savoir ce qu’est un ENT</p>, <p>Connaître les fonctionnalités principales d’un ENT</p>, <p>Utiliser le compte parent de manière adaptée</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'eeeb4951-6f38-4467-a4ba-0c85ed71321a',
      'shortId': '27d6ca4f',
      'slug': 'demo-combinix-1',
      'title': 'Demo combinix 1',
      'filename': 'demo-combinix-1.json',
      'level': 'novice',
      'duration': 1,
      'objectives': 'Test parcours combiné',
      'isBeta': true,
      'visibility': 'private',
    },
    {
      'id': 'f32a2238-4f65-4698-b486-15d51935d335',
      'shortId': 'df82ec66',
      'slug': 'demo-combinix-2',
      'title': 'Demo combinix 2',
      'filename': 'demo-combinix-2.json',
      'level': 'novice',
      'duration': 1,
      'objectives': 'Test parcours combiné 2',
      'isBeta': true,
      'visibility': 'private',
    },
    {
      'id': '235c680e-cbd2-4c56-bef6-80d3ed4d417a',
      'shortId': '0aefd71f',
      'slug': 'demo-epreuves-components',
      'title': 'Démonstration des composants Pix Épreuves',
      'filename': 'demo-epreuves-components.json',
      'level': 'novice',
      'duration': 2,
      'objectives': '<p>Non régression sur les composants Pix Épreuves.</p>',
      'isBeta': true,
      'visibility': 'private',
    },
    {
      'id': 'ab82925d-4775-4bca-b513-4c3009ec5886',
      'shortId': 'f2eeb056',
      'slug': 'demo-llm',
      'title': 'Démo LLM',
      'filename': 'demo-llm.json',
      'level': 'novice',
      'duration': 2,
      'objectives': '<p>Démonstration</p>',
      'isBeta': true,
      'visibility': 'private',
    },
    {
      'id': '65b761ab-3ebd-44a9-84b7-8b5e151aee76',
      'shortId': '00832162',
      'slug': 'distinguer-vrai-faux-sur-internet',
      'title': 'Les informations sur internet : distinguer le vrai du faux',
      'filename': 'distinguer-vrai-faux-sur-internet.json',
      'level': 'independent',
      'duration': 10,
      'objectives': 'Connaître une méthode de vérification d‘informations, Savoir vérifier une information sur internet, Repérer une fausse information sur internet',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '1b33d6ab-ebfe-49fa-8568-8c40471b4baa',
      'shortId': 'b9414fc3',
      'slug': 'galerie',
      'title': 'Galerie Modulix',
      'filename': 'galerie.json',
      'level': 'novice',
      'duration': 1,
      'objectives': '<p>Découvrir les éléments de la galerie Modulix</p>',
      'isBeta': true,
      'visibility': 'private',
    },
    {
      'id': 'bbc48a68-6bef-4261-89f0-86459413c10c',
      'shortId': '0426c3c5',
      'slug': 'ia-cadre-usage-educ-nov',
      'title': ' IA et éducation, découverte du cadre d’usage',
      'filename': 'ia-cadre-usage-educ-nov.json',
      'level': 'novice',
      'duration': 10,
      'objectives': 'Connaître les finalités du cadre d’usage de l’IA en éducation, Identifier les repères essentiels proposés par ce cadre, Développer un usage maîtrisé des IA génératives conformément à ses préconisations',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'c7fe268a-9371-4eec-8a8a-df79c7479a46',
      'shortId': 'a23e9d63',
      'slug': 'ia-deepfakes-alt',
      'title': 'Les deepfakes (hypertrucages) : c’est quoi ?',
      'filename': 'ia-deepfakes-alt.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Savoir que des médias en ligne peuvent être créés avec l‘intelligence artificielle (IA)</p>, <p>Connaître la notion de deepfake (hypertrucage)</p>, <p>Repérer les intentions des auteurs de deepfakes (hypertrucages)</p>',
      'isBeta': true,
      'visibility': 'private',
    },
    {
      'id': '875df1ff-27c1-4b41-a0a8-5ff46013f35e',
      'shortId': '87edbdda',
      'slug': 'jeux-video-enfant',
      'title': 'Choisir un jeu vidéo adapté à son enfant',
      'filename': 'jeux-video-enfant.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Identifier des informations clés au sujet d’un jeu vidéo</p>, <p>Vérifier si un jeu vidéo est adapté à l’âge d’un enfant grâce à la signalétique PEGI</p>, <p>Vérifier si un jeu vidéo propose des achats intégrés et des échanges avec d’autres joueurs.</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '8bdec793-7508-41b4-9df2-e1cf96969680',
      'shortId': '3e5fa7fc',
      'slug': 'mots-de-passe-securises',
      'title': 'Des mots de passe solides',
      'filename': 'mots-de-passe-securises.json',
      'level': 'novice',
      'duration': 12,
      'objectives': 'Comprendre l‘intérêt d‘avoir des mots de passe solides, Connaître les principaux risques liés aux mots de passe, Savoir créer un mot de passe solide',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'e2b42968-4797-46e7-b9ca-11d0d0dfa978',
      'shortId': 'dc38a091',
      'slug': 'metaux-eau-reemploi',
      'title': 'Le numérique : pourquoi privilégier le réemploi ?',
      'filename': 'nr_durabilite_ind.json',
      'level': 'independent',
      'duration': 10,
      'objectives': '<p>Connaître les métaux et terres rares qui composent les appareils numériques (ordinateurs, tablettes, smarphones...).</p>, <p>Identifier les principaux impacts environnementaux liés à l’extraction des métaux et terres rares.</p>, <p>Comprendre l’intérêt du réemploi et du reconditionnement pour réduire l’impact environnemental.</p>',
      'isBeta': false,
      'visibility': 'public',
    },
    {
      'id': '12cd102f-9831-4264-8d5e-15a8f177594a',
      'shortId': '4af95e9a',
      'slug': 'ports-connexions-essentiels',
      'title': 'Les ports de connexion d’un ordinateur',
      'filename': 'ports-connexions-essentiels.json',
      'level': 'novice',
      'duration': 10,
      'objectives': '<p>Reconnaître les ports de connexion essentiels d’un ordinateur</p>, <p>Connaître la fonction de chaque port de connexion</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'a64d1ca8-5222-464a-ae0c-e8bbdf949e18',
      'shortId': '8c6d595b',
      'slug': 'principes-fondateurs-wikipedia',
      'title': 'Les principes fondateurs de Wikipédia',
      'filename': 'principes-fondateurs-wikipedia.json',
      'level': 'independent',
      'duration': 10,
      'objectives': 'Comprendre les principes fondateurs de Wikipédia, Connaître certaines caractéristiques et fonctionnalités de Wikipédia, Trouver des informations dans un article Wikipédia',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '68f92c57-9e66-4258-a2f4-b71fad7ab004',
      'shortId': '9434a1a4',
      'slug': 'sources-informations',
      'title': 'Les sources d‘information',
      'filename': 'sources-informations.json',
      'level': 'novice',
      'duration': 10,
      'objectives': 'Rechercher la source d’une information, Connaître les différents types de sources d’information, Repérer si une source d’information est fiable',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '08ef1a47-b691-4138-b899-39f3512fa152',
      'shortId': 'f0506561',
      'slug': 'tmp08ef',
      'title': 'Derrière le prompt : comment fonctionnent les IA génératives ?',
      'filename': 'tmp08ef.json',
      'level': 'independent',
      'duration': 10,
      'objectives': '<p>Comprendre comment un système d’IA générative produit un texte ou une image</p>, <p>Comprendre les fondamentaux du fonctionnement des systèmes d‘iA générative</p>, <p>Identifier les limites d‘un système d‘iA générative</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '19468565-a56b-4aa5-9bf0-369e94bc85ea',
      'shortId': 'ed36b111',
      'slug': 'tri-multicritere-tableau',
      'title': 'Trier un tableau selon plusieurs critères',
      'filename': 'tri-multicritere-tableau.json',
      'level': 'advanced',
      'duration': 10,
      'objectives': '<p>Identifier des situations qui nécessitent un tri multicritère</p>, <p>Trier des données sur tableur selon plusieurs critères</p>, <p>Utiliser des critères de tris avancés</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': 'e8cee13e-1d4d-47eb-bd26-d7ea6a10b1e6',
      'shortId': '3858d191',
      'slug': 'utiliser-souris-ordinateur-1',
      'title': 'Utiliser une souris d’ordinateur - 1',
      'filename': 'utiliser-souris-ordinateur-1.json',
      'level': 'novice',
      'duration': 30,
      'objectives': '<p>Reconnaître une souris et connaître son utilité</p>, <p>Prendre en main une souris et la déplacer</p>, <p>Effectuer ses premiers clics gauche</p>',
      'isBeta': true,
      'visibility': 'public',
    },
    {
      'id': '1f425bc6-7a35-4ceb-9634-a25da1e36233',
      'shortId': 'f59200bf',
      'slug': 'utiliser-souris-ordinateur-2',
      'title': 'Utiliser une souris d’ordinateur - 2',
      'filename': 'utiliser-souris-ordinateur-2.json',
      'level': 'novice',
      'duration': 30,
      'objectives': '<p>Connaître l’utilité des principaux boutons de la souris</p>, <p>Utiliser la molette de la souris</p>, <p>Effectuer ses premiers clics droit et double-clics</p>',
      'isBeta': true,
      'visibility': 'public',
    },
  ]);
}

export { getLearningContent };
